# I2C
CONFIG_I2C=y #I2C_SAM0 included

# Networking core
CONFIG_NETWORKING=y #enables generic link layer and networking support and is the basis for higher level protocols (e.g. IP protocols).
CONFIG_NET_IPV4=y #device is able to send and receive IPv4 network packets
CONFIG_NET_TCP=y #HTTP uses TCP,depends on NET_IP which depends on NET_IPV4(NET_UDP not needed)
CONFIG_NET_ARP=y # Address Resolution Protocol maps IP addr to MAC address(if disabled, MCU doesnt send packets to browser)

# HTTP server
CONFIG_HTTP_SERVER=y #can start a HTTP server threead,open TCP socket,bind to port 8080, listen to clients, sends requests to handlers
CONFIG_HTTP_SERVER_CAPTURE_HEADERS=y #enables HTTP server to store selected "request headers". These "request header" are given to Java Script handler along with temperature value
CONFIG_HTTP_SERVER_CAPTURE_HEADER_COUNT=1

# Static IPv4 (same as your working app)
CONFIG_NET_CONFIG_SETTINGS=y #init`s the network interface, like applying IPv4 addr to MCU 
CONFIG_NET_CONFIG_AUTO_INIT=y #applies the settings in CONFIG_SETTINGS at boot

# Set static IP address for board


CONFIG_NET_CONFIG_MY_IPV4_NETMASK="255.255.255.0"

CONFIG_LOG=y
